[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  "@chainlink/=lib/chainlink/contracts/src/v0.8/interfaces/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@custom-interfaces/=lib/interfaces/",
  "@library/=lib/library/",
]
