[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# configuration needed when working with OpenZeppelins Foundry Upgrades. see https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades
build_info = true
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  "@chainlink/=lib/chainlink/contracts/src/v0.8/interfaces/",
  "@openzeppelin/contracts-default/=lib/openzeppelin-contracts/contracts/",
  "@custom-interfaces/=lib/interfaces/",
  "@library/=lib/library/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
