[profile.default]
libs = ["lib"]
out = "out"
src = "src"
via-ir = true

# remappings = [
#   "@chainlink/=lib/chainlink/contracts/src/v0.8/interfaces/",
#   "@openzeppelin/contracts-default/=lib/openzeppelin-contracts/contracts/",
#   "@custom-interfaces/=src/interfaces/",
#   "@library/=src/library/",
#   "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
#   "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
# ]